### PR TITLE
Fix faulty logic for `wpmu_new_blog` filter

### PR DESCRIPTION
**Pull request by brianfeister**
for typecast array that injects a single item with EMPTY as value in wp_sitemeta->pm_auto_activate_list table

### CODE REVIEW

**Comment by brianfeister** [comment]
Submitting this PR because this crashed my custom signup process for my Multisite Install, was trying to activate plugins a plugin array that looks like this:

```
$auto_activate === array( 'EMPTY' );
```

This is stored in the network table `wp_sitemeta->pm_auto_activate_list`.

The logic is fine if there are `>=` 1 plugins with auto-activate enabled.

**Comment by brianfeister** [comment]
Sorry for the extra whitespace, I have my IDE set to trim trailing whitespace, you can see the clean diff here: 
https://github.com/wp-repository/wpmu-plugin-manager/pull/1/files?w=1

**Comment by brianfeister** [comment]
My apologies, I noticed the plugin was broken for me and didn't bother to test yours before I "fixed" it, it seems that you have already addressed this issue somewhere else, as I am now testing your code and it seems to work fine without this change. 

Cheers!

**Comment by cfoellmann** [comment]
@brianfeister no problem.
I am going to release the plugin/fork on wp.org so it is easier to update. If you have any problems and/or suggestions just open an issue here on github

**Pull request closed without merging**
